server:
  port: 8002
  servlet:
    context-path: /api

db:
  host: "${DB_HOST:localhost}"
  port: "${DB_PORT:3306}"
  name: "${DB_NAME:cards}"
  user: "${DB_USER:root}"
  password: "${DB_PASSWORD:password}"

# swagger-ui custom path
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: cards
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${db.user}
    password: ${db.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # Use MySQL8Dialect if you're on MySQL 8.x
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: jdbc:mysql://${db.host}:${db.port}/${db.name}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    user: ${db.user}
    password: ${db.password}
    schemas: ${db.name}
    default-schema: ${db.name}
    locations: classpath:db/migration
    table: flyway_schema_history_cards
  config:
    import: "${SPRING_CLOUD_CONFIG_URL:optional:configserver:http://localhost:8071/}"
  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: "${RABBITMQ_PORT:5672}"
    username: "${RABBITMQ_USERNAME:guest}"
    password: "${RABBITMQ_PASSWORD:guest}"
    virtual-host: "${RABBITMQ_VIRTUAL_HOST:vh_host}"

info:
  app:
    name: "cards"
    description: "Easy Bank Accounts Application"
    version: "1.0.0"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "${EUREKA_SERVER_URL:http://localhost:8761/eureka/}"
