name: "architecture"

services:
  mysql:
    image: mysql:8.0-bookworm
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: microservices
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
    - "3306:3306"
    volumes:
    - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword" ]
      timeout: 10s
      retries: 3
      interval: 15s
      start_period: 10s
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.25
    networks:
    - network1

  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq
    ports:
    - "15672:15672"
    - "5672:5672"
    volumes:
    - rabbitmq_data:/var/lib/rabbitmq
    environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
    - RABBITMQ_DEFAULT_VHOST=vh_hosts
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.25
    networks:
    - network1
    restart: unless-stopped

volumes:
  mysql_data:
    name: mysql_data
  rabbitmq_data:
    name: rabbitmq_data

networks:
  network1:
    name: docker_network
    external: true
