# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: eurekaserver-deployment
serviceName: eurekaserver
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 1

image:
  repository: vanhieuit10/easybank
  tag: eurekaserver

containerPort: 8761

service:
  type: ClusterIP
  port: 8761
  targetPort: 8761

is_config_server: false
app_name_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: false
resource_server_enabled: false
rabbitmq_enabled: false
mysql_enabled: false
otel_enabled: true