services:
  network-deploy-service:
    networks:
    - network1

  microservices-base-config:
    extends: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_VIRTUAL_HOST: vh_hosts

  microservice-configserver-config:
    extends: microservices-base-config
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
