name: "microservices"

services:
  configserver:
    image: configserver:1.0
    container_name: configserver
    ports:
      - "8071:8071"
    environment:
      - SPRING_PROFILES_ACTIVE=git
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservices-configserver-config

  eurekaserver:
    image: eurekaserver:1.0
    container_name: eurekaserver
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservices-eureka-config
    depends_on:
      configserver:
        condition: service_healthy

  gateway:
    image: gatewayserver:1.0
    container_name: gateway
    ports:
      - "8072:8072"
    healthcheck:
      test: "curl --fail --silent localhost:8072/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservices-gateway-config

  accounts:
    image: accounts:1.0
    container_name: accounts
    ports:
      - 8001:8001
    environment:
      - DB_NAME=accounts
    depends_on:
      gateway:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservices-service-config
  
  cards:
    image: cards:1.0
    container_name: cards
    ports:
      - "8002:8002"
    environment:
      - DB_NAME=cards
    depends_on:
      gateway:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservices-service-config
  
  loans:
    image: loans:1.0
    container_name: loans
    ports:
      - "8003:8003"
    environment:
      - DB_NAME=loans
    depends_on:
      gateway:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservices-service-config

networks:
  network1:
    name: docker_network
    external: true