server:
  port: 8003
  servlet:
    context-path: /api

# swagger-ui custom path
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: loans
  profiles:
    active: prod
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/loans?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Use MySQL8Dialect if you're on MySQL 8.x
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/loans?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    user: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
    schemas: ${MYSQL_SCHEMA:loans}
    default-schema: ${MYSQL_SCHEMA:loans}
    locations: classpath:db/migration
    table: flyway_schema_history_loans
  config:
    import: optional:configserver:http://localhost:8071

management:
  endpoints:
    web:
      exposure:
        include: "*"