server:
  port: 8003
spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3306/cards?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Use MySQL8Dialect if you're on MySQL 8.x
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: jdbc:mysql://localhost:3306/loans?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    user: root
    password: password
    schemas: loans
    default-schema: loans
    locations: classpath:db/migration
    table: flyway_schema_history_loans
