build:
  version: 1.0

loans:
  message: "Welcome to EasyBank Loans related local API"
  contactDetails:
    name: "Hieu Van - Developer"
    email: "vanhieuit10@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

otel:
  service:
    name: ${spring.application.name}
  resource:
    attributes:
      deployment.environment: ${SPRING_PROFILES_ACTIVE:dev}
      service.version: ${project.version:1.0.0}
      host.name: ${HOSTNAME:unknown}
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
      protocol: grpc
      timeout: 10s
      compression: gzip
    logs:
      exporter: ${OTEL_EXPORTER_LOGS_ENABLED:none}
    traces:
      exporter: ${OTEL_EXPORTER_TRACES_ENABLED:none}
    metrics:
      exporter: ${OTEL_EXPORTER_METRICS_ENABLED:none}
  logs:
    enabled: true
  traces:
    sampler: parentbased_always_on
  bsp:
    schedule:
      delay: 5000
    max:
      queue:
        size: 2048
      export:
        batch:
          size: 512
    export:
      timeout: 30000
  blrp:
    schedule:
      delay: 1000
    max:
      queue:
        size: 2048
      export:
        batch:
          size: 512
    export:
      timeout: 30000
  bmep:
    schedule:
      delay: 10000
    max:
      queue:
        size: 2048
      export:
        batch:
          size: 512
    export:
      timeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
    access:
      default: UNRESTRICTED
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: W3C