build:
  version: 1.0

accounts:
  message: "Welcome to EasyBank accounts related local API"
  contactDetails:
    name: "Hieu Van - Developer"
    email: "vanhieuit10@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345