server:
  port: 8001
  servlet:
    context-path: /api

# swagger-ui custom path
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
spring:
  application:
    name: accounts
  profiles:
    active: "prod"
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/accounts?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Use MySQL8Dialect if you're on MySQL 8.x
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/accounts?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    user: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
    schemas: ${MYSQL_SCHEMA:accounts}
    default-schema: ${MYSQL_SCHEMA:accounts}
    locations: classpath:db/migration
    table: flyway_schema_history_accounts
  config:
    import: "${SPRING_CLOUD_CONFIG_URL}"
  rabbitmq:
    host: "${RABBITMQ_HOST}"
    port: "${RABBITMQ_PORT}"
    username: "${RABBITMQ_USERNAME}"
    password: "${RABBITMQ_PASSWORD}"
    virtual-host: "${RABBITMQ_VIRTUAL_HOST}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true