plugins {
    id 'java-library'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
    id 'maven-publish'
}

group = "${group}"
version = "${version}"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

ext {
    set("springCloudVersion", "2024.0.1")
//    set("openTelemetryVersion", "2.16.0")
//    set("logbackAppenderVersion", "2.10.0-alpha")
}

repositories {
    mavenCentral()
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-actuator'

//    implementation(platform("io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom:2.10.0"))

//    implementation("io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter")
//    implementation("io.opentelemetry.instrumentation:opentelemetry-logback-appender-1.0:2.10.0-alpha")
//    implementation("io.opentelemetry:opentelemetry-api")
//    implementation("io.opentelemetry:opentelemetry-sdk")
//    implementation("io.opentelemetry:opentelemetry-sdk-extension-autoconfigure")
//    implementation("io.opentelemetry:opentelemetry-exporter-otlp")
//    implementation("io.opentelemetry:opentelemetry-sdk-metrics")
//    implementation("io.opentelemetry.instrumentation:opentelemetry-logback-mdc-1.0:2.10.0-alpha")
//    implementation("io.opentelemetry:opentelemetry-extension-trace-propagators")
//    implementation("io.micrometer:micrometer-tracing-bridge-otel")

    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    // https://mvnrepository.com/artifact/org.axonframework/axon-server-connector
//    api 'org.axonframework:axon-server-connector:4.12.1'
//    api 'org.axonframework:axon-bom:4.12.1'

    // https://mvnrepository.com/artifact/org.axonframework/axon-spring-boot-starter
    // Use 'api' to expose Axon Framework to consuming projects
    api 'org.axonframework:axon-spring-boot-starter:4.12.1'
}

// Disable bootJar for library projects
tasks.named('bootJar') {
    enabled = false
}

// Enable plain jar for library publishing
tasks.named('jar') {
    enabled = true
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = "hieunv.dev"
            artifactId = 'commonlib'
            version = "1.0.0"
        }
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(GenerateModuleMetadata) {
    suppressedValidationErrors.add('dependencies-without-versions')
}