spring:
  application:
    name: configserver
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///D:/dev/microservices//config"
        git:

          uri: https://github.com/vanhieuhp/microservices.git
          default-label: "feature/pet-project"
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths: config_properties

encrypt:
  key: "encrypt-key-please-change-me"

server:
  port: 8071