spring:
  application:
    name: configserver
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///D:/dev/microservices//config"
        git:
          uri: https://github.com/vanhieuhp/microservices.git
          default-label: "feature/springcloud"
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths: config_properties

  rabbitmq:
    host: "${RABBITMQ_HOST}"
    port: "${RABBITMQ_PORT}"
    username: "${RABBITMQ_USERNAME}"
    password: "${RABBITMQ_PASSWORD}"
    virtual-host: "${RABBITMQ_VIRTUAL_HOST}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "encrypt-key-please-change-me"

server:
  port: 8071