spring:
  application:
    name: configserver
  profiles:
    active: native
#    active: git
  cloud:
    config:
      server:
        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///D:/dev/microservices//config"
          search-locations: "file:////home/hieunv/projects/microservices/infrastructure/config_properties"
        git:
          uri: https://github.com/vanhieuhp/microservices.git
          default-label: "feature/springcloud"
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths: infrastructure/config_properties

  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: "${RABBITMQ_PORT:5672}"
    username: "${RABBITMQ_USERNAME:guest}"
    password: "${RABBITMQ_PASSWORD:guest}"
    virtual-host: "${RABBITMQ_VIRTUAL_HOST:vh_host}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "encrypt-key-please-change-me"

server:
  port: 8071