global:
  scrape_interval: 15s # How frequently to scrape targets by default
  evaluation_interval: 15s # How frequently to evaluate rules

    # Alertmanager configuration
    # alerting:
    # alertmanagers:
    # - static_configs:
    # - targets:
  # - alertmanager:9093 # Alertmanager's HTTP endpoint (default port)

# Load rule files and periodically evaluate them according to the global 'evaluation_interval'
# rule_files:
# - "rules.ym/l" # Path to your alerting rules

scrape_configs:
  - job_name: "otel-collector"
    # Scrape metrics from the OpenTelemetry Collector
    static_configs:
      - targets: ["otel-collector:8889"] # Scrape endpoint for Prometheus
    # metrics_relabel_configs:
    #   - source_labels: [__name__]
    #     regex: "unwanted_metric_prefix_.*"
    #     action: drop

  # Example: Scrape Prometheus itself (optional, good for monitoring Prometheus health)
  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ['localhost:9090']