apiVersion: v1
kind: Secret
metadata:
  name: microservices-secret
  namespace: microservices
type: Opaque
stringData:
  DB_HOST: 192.168.1.8
  DB_PORT: "3306"
  DB_USER: root
  DB_PASSWORD: password
  SPRING_CLOUD_CONFIG_URL: configserver:http://configserver-service.microservices.svc.cluster.local:8071
  RABBITMQ_HOST: 192.168.1.8
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
  RABBITMQ_VIRTUAL_HOST: vh_hosts
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mysql-secrets
#   namespace: microservices
# type: Opaque
# stringData:
#   MYSQL_ROOT_PASSWORD: password # password
#   MYSQL_DATABASE: theschool # theschool
#   MYSQL_USER: theschool # theschool
#   MYSQL_PASSWORD: password # password
