apiVersion: v1
kind: Secret
metadata:
  name: accounts-secret
  namespace: microservices
type: Opaque
stringData:
  DB_NAME: accounts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-deployment
  template:
    metadata:
      labels:
        app: accounts-deployment
    spec:
      containers:
      - name: accounts-deployment
        image: accounts:1.0
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8001
        envFrom:
        - secretRef:
            name: microservices-secret
        - secretRef:
            name: accounts-secret
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health/liveness
        #     port: 8001
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health/readiness
        #     port: 8001
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: microservices
spec:
  selector:
    app: accounts-deployment
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
---


