apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver-deployment
  template:
    metadata:
      labels:
        app: configserver-deployment
    spec:
      containers:
      - name: configserver-deployment
        image: configserver:1.0
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8071
        envFrom:
        - secretRef:
            name: microservices-secret
---
apiVersion: v1
kind: Service
metadata:
  name: configserver-service
  namespace: microservices
spec:
  selector:
    app: configserver-deployment
  ports:
  - port: 8071
    targetPort: 8071
  type: ClusterIP
---


