apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mysql
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /nfs/share/external/mysql
    server: 192.168.1.37
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-mysql
  namespace: microservices
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-storage
---
# StatefulSet for MySQL
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-server
  namespace: microservices
spec:
  serviceName: mysql-server
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
      - name: mysql-server
        image: mysql:8.0-bookworm
        resources:
          limits:
            memory: "1024Mi" # Increased for better performance
            cpu: "1000m"
          requests:
            memory: "1024Mi" # Added requests for better resource management
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: mysql-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: microservices
        - name: MYSQL_USER
          value: microservices
        - name: MYSQL_PASSWORD
          value: password
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pvc
        emptyDir: {}
      # livenessProbe:
      #   exec:
      #     command: [ "mysqladmin", "ping", "-h", "localhost" ]
      #   initialDelaySeconds: 30
      #   periodSeconds: 10
      # readinessProbe:
      #   exec:
      #     command: [ "mysqladmin", "ping", "-h", "localhost" ]
      #   initialDelaySeconds: 5
      #   periodSeconds: 5


      #   valueFrom:
      #     secretKeyRef:
      #       name: mysql-secrets
      #       key: MYSQL_ROOT_PASSWORD
      # - name: MYSQL_DATABASE
      #   valueFrom:
      #     secretKeyRef:
      #       name: mysql-secrets
      #       key: MYSQL_DATABASE
      # - name: MYSQL_USER
      #   valueFrom:
      #     secretKeyRef:
      #       name: mysql-secrets
      #       key: MYSQL_USER
      # - name: MYSQL_PASSWORD
      #   valueFrom:
      #     secretKeyRef:
      #       name: mysql-secrets
      #       key: MYSQL_PASSWORD
      #   volumeMounts:
      #   - name: mysql-pvc
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-pvc
      #   persistentVolumeClaim:
      #     claimName: nfs-pvc-mysql
---
# Headless Service for MySQL
apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  namespace: microservices
spec:
  selector:
    app: mysql-server
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-port
  type: ClusterIP
